"use client";
import { Facescape } from "@/components/ui/facescape";

export default function FacescapeDemo() {
  const avatars = [
    {
      src: "https://github.com/Adityakishore0.png",
      alt: "@Ahdeetai",
      fallback: "AK",
      name: "Ahdeetai",
    },
    {
      src: "https://github.com/shivam785.png",
      alt: "@shivam785",
      fallback: "S",
      name: "kumar shivam",
    },
    {
      src: "https://github.com/PhatJack.png",
      alt: "@PhatJack",
      fallback: "JP",
      name: "Jack Phat",
    },
    {
      src: "https://github.com/isouravanand.png",
      alt: "@isouravanand",
      fallback: "SA",
      name: "isouravanand",
    },
    {
      src: "https://github.com/srikarnarayanempati.png",
      alt: "@srikarnarayanempati",
      fallback: "SE",
      name: "Srikar Empati",
    },
    {
      src: "https://github.com/gautamkaran.png",
      alt: "@gautamkaran",
      fallback: "KG",
      name: "K K Gautam",
    },
    {
      src: "https://github.com/Abhinav-456.png",
      alt: "@Abhinav-456",
      fallback: "A",
      name: "Abhinav",
    },
    {
      src: "https://github.com/Roshan181.png",
      alt: "@Roshan181",
      fallback: "RM",
      name: "Roshan",
    },
    {
      src: "https://github.com/CarlosSousa2001.png",
      alt: "@CarlosSousa2001",
      fallback: "CS",
      name: "Carlos Sousa",
    },
    {
      src: "https://github.com/albermav.png",
      alt: "@tj",
      fallback: "AL",
      name: "albermav",
    },
    {
      src: "https://github.com/dwin-gharibi.png",
      alt: "@dwin-gharibi",
      fallback: "DG",
      name: "Dwin Gharibi",
    },
    {
      src: "https://github.com/AlexanderAbramovPav.png",
      alt: "@AlexanderAbramovPav",
      fallback: "AP",
      name: "A AbramovPav",
    },
    {
      src: "https://github.com/MiladJoodi.png",
      alt: "@MiladJoodi",
      fallback: "MJ",
      name: "Milad Joodi",
    },
    {
      src: "https://github.com/micaelcf.png",
      alt: "@micaelcf",
      fallback: "ML",
      name: "micaelcf",
    },
    {
      src: "https://github.com/sahillangoo.png",
      alt: "@sahillangoo",
      fallback: "S",
      name: "sahillangoo",
    },
    {
      src: "https://github.com/joaogabriel-sg.png",
      alt: "@joaogabriel-sg",
      fallback: "JR",
      name: "João Gabriel",
    },
    {
      src: "https://github.com/shivam785.png",
      alt: "@shivam785",
      fallback: "S",
      name: "Kumar shivam",
    },
    {
      src: "https://github.com/PhatJack.png",
      alt: "@PhatJack",
      fallback: "JP",
      name: "Jack Phat",
    },
    {
      src: "https://github.com/isouravanand.png",
      alt: "@isouravanand",
      fallback: "SA",
      name: "isouravanand",
    },
    {
      src: "https://github.com/srikarnarayanempati.png",
      alt: "@srikarnarayanempati",
      fallback: "SE",
      name: "Srikar Empati",
    },
    {
      src: "https://github.com/gautamkaran.png",
      alt: "@gautamkaran",
      fallback: "KG",
      name: "K K Gautam",
    },
    {
      src: "https://github.com/Abhinav-456.png",
      alt: "@Abhinav-456",
      fallback: "A",
      name: "Abhinav",
    },
    {
      src: "https://github.com/Roshan181.png",
      alt: "@Roshan181",
      fallback: "RM",
      name: "Roshan",
    },
    {
      src: "https://github.com/CarlosSousa2001.png",
      alt: "@CarlosSousa2001",
      fallback: "CS",
      name: "Carlos Sousa",
    },
    {
      src: "https://github.com/albermav.png",
      alt: "@tj",
      fallback: "AL",
      name: "albermav",
    },
    {
      src: "https://github.com/dwin-gharibi.png",
      alt: "@dwin-gharibi",
      fallback: "DG",
      name: "Dwin Gharibi",
    },
    {
      src: "https://github.com/AlexanderAbramovPav.png",
      alt: "@AlexanderAbramovPav",
      fallback: "AP",
      name: "A AbramovPav",
    },
    {
      src: "https://github.com/MiladJoodi.png",
      alt: "@MiladJoodi",
      fallback: "MJ",
      name: "Milad Joodi",
    },
    {
      src: "https://github.com/micaelcf.png",
      alt: "@micaelcf",
      fallback: "ML",
      name: "micaelcf",
    },
    {
      src: "https://github.com/sahillangoo.png",
      alt: "@sahillangoo",
      fallback: "S",
      name: "sahillangoo",
    },
    {
      src: "https://github.com/shivam785.png",
      alt: "@shivam785",
      fallback: "S",
      name: "Kumar shivam",
    },
    {
      src: "https://github.com/PhatJack.png",
      alt: "@PhatJack",
      fallback: "JP",
      name: "Jack Phat",
    },
    {
      src: "https://github.com/isouravanand.png",
      alt: "@isouravanand",
      fallback: "SA",
      name: "isouravanand",
    },
    {
      src: "https://github.com/srikarnarayanempati.png",
      alt: "@srikarnarayanempati",
      fallback: "SE",
      name: "Srikar Empati",
    },
    {
      src: "https://github.com/gautamkaran.png",
      alt: "@gautamkaran",
      fallback: "KG",
      name: "K K Gautam",
    },
    {
      src: "https://github.com/Abhinav-456.png",
      alt: "@Abhinav-456",
      fallback: "A",
      name: "Abhinav",
    },
    {
      src: "https://github.com/Roshan181.png",
      alt: "@Roshan181",
      fallback: "RM",
      name: "Roshan",
    },
    {
      src: "https://github.com/CarlosSousa2001.png",
      alt: "@CarlosSousa2001",
      fallback: "CS",
      name: "Carlos Sousa",
    },
    {
      src: "https://github.com/albermav.png",
      alt: "@tj",
      fallback: "AL",
      name: "albermav",
    },
    {
      src: "https://github.com/dwin-gharibi.png",
      alt: "@dwin-gharibi",
      fallback: "DG",
      name: "Dwin Gharibi",
    },
    {
      src: "https://github.com/AlexanderAbramovPav.png",
      alt: "@AlexanderAbramovPav",
      fallback: "AP",
      name: "A AbramovPav",
    },
    {
      src: "https://github.com/isouravanand.png",
      alt: "@isouravanand",
      fallback: "SA",
      name: "isouravanand",
    },
    {
      src: "https://github.com/srikarnarayanempati.png",
      alt: "@srikarnarayanempati",
      fallback: "SE",
      name: "Srikar Empati",
    },
    {
      src: "https://github.com/gautamkaran.png",
      alt: "@gautamkaran",
      fallback: "KG",
      name: "K K Gautam",
    },
    {
      src: "https://github.com/Abhinav-456.png",
      alt: "@Abhinav-456",
      fallback: "A",
      name: "Abhinav",
    },
    {
      src: "https://github.com/MiladJoodi.png",
      alt: "@MiladJoodi",
      fallback: "MJ",
      name: "Milad Joodi",
    },
    {
      src: "https://github.com/micaelcf.png",
      alt: "@micaelcf",
      fallback: "ML",
      name: "micaelcf",
    },
    {
      src: "https://github.com/sahillangoo.png",
      alt: "@sahillangoo",
      fallback: "S",
      name: "sahillangoo",
    },
  ];

  return <Facescape variant="circle" avatars={avatars} colorDuration={3000} />;
}
